language: python

env:
    - BUILD=tests
    - BUILD=style

python:
    - 2.7
    - pypy
    - 3.4

before_install:
  - sudo apt-get update && sudo apt-get --reinstall install -qq language-pack-de

install: pip install tox

script:
    - ./.travis.run.sh

matrix:
    exclude:
        - python: pypy
          env: BUILD=style
