language: python
os: linux

python:
    - 3.5
    - 3.6
    - 3.7
    - 3.8
    - 3.9
    - "nightly"

env:
    - BUILD=py

jobs:
    include:
      - python: 3.9
        env: BUILD=style
      - python: 3.9
        env: BUILD=docs
      - python: 3.9
        env: BUILD=mypy
      - python: 3.9
        env: BUILD=pytz201610
      - python: 3.9
        env: BUILD=pytz201702
    allow_failures:
      - python: "nightly"

addons:
    apt:
        packages:
            - language-pack-de

install:
        - "pip install tox"

script:
    - "tox -e $BUILD"
